name: A workflow for PROJECT MAXWELL
on: push

jobs:
  build:
    name: Project Maxwell action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Build Docker Image
        run: docker build -t maxwellimage .
      - name: Run image
        run: docker run --name maxwellcontainer -d maxwellimage
      - name: view logs
        run: docker logs maxwellcontainer
